
package com.k_int.sushiServerToolkit.vanilla;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-05-04T21:14:09.836+01:00
 * Generated source version: 3.1.3
 * 
 */
public final class SushiServiceInterface_SushiServicePort_Client {

    private static final QName SERVICE_NAME = new QName("SushiService", "SushiService");

    private SushiServiceInterface_SushiServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SushiService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SushiService ss = new SushiService(wsdlURL, SERVICE_NAME);
        SushiServiceInterface port = ss.getSushiServicePort();  
        
        {
        System.out.println("Invoking getReport...");
        com.k_int.sushiServerToolkit.vanilla.ReportRequest _getReport_messagePart = new com.k_int.sushiServerToolkit.vanilla.ReportRequest();
        com.k_int.sushiServerToolkit.vanilla.ReportResponse _getReport__return = port.getReport(_getReport_messagePart);
        System.out.println("getReport.result=" + _getReport__return);


        }

        System.exit(0);
    }

}
