package com.k_int.sushiServerToolkit.counter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-05-04T21:14:10.062+01:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "SushiService", name = "SushiServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SushiServiceInterface {

    @WebMethod(operationName = "GetReport", action = "SushiService:GetReportIn")
    @WebResult(name = "ReportResponse", targetNamespace = "http://www.niso.org/schemas/sushi/counter", partName = "messagePart")
    public CounterReportResponse getReport(
        @WebParam(partName = "messagePart", name = "ReportRequest", targetNamespace = "http://www.niso.org/schemas/sushi/counter")
        ReportRequest messagePart
    );
}
