package com.k_int.sushiServerToolkit.counter;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-05-04T21:14:10.065+01:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "SushiService", 
                  wsdlLocation = "file:contracts/counter_sushi/counter_sushi4_1.wsdl",
                  targetNamespace = "SushiService") 
public class SushiService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("SushiService", "SushiService");
    public final static QName SushiServicePort = new QName("SushiService", "SushiServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:contracts/counter_sushi/counter_sushi4_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SushiService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:contracts/counter_sushi/counter_sushi4_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SushiService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SushiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SushiService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SushiService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SushiService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SushiService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SushiServiceInterface
     */
    @WebEndpoint(name = "SushiServicePort")
    public SushiServiceInterface getSushiServicePort() {
        return super.getPort(SushiServicePort, SushiServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SushiServiceInterface
     */
    @WebEndpoint(name = "SushiServicePort")
    public SushiServiceInterface getSushiServicePort(WebServiceFeature... features) {
        return super.getPort(SushiServicePort, SushiServiceInterface.class, features);
    }

}
